import { useState, useMemo, useEffect } from 'react';
import Sidebar from '../../components/Sidebar';
import { useInvoices } from '../../hooks/useInvoices';
import { useDeductions } from '../../hooks/useDeductions';
import { useTaxCalculation } from '../../hooks/useTaxCalculation';
import { formatCurrency } from '../../utils/validators';

const currentYearForList = new Date().getFullYear();
const YEARS = Array.from({ length: 5 }, (_, i) => currentYearForList - i);

function FilingSummaryPage() {
  const currentYear = new Date().getFullYear();
  const [year, setYear] = useState(currentYear);
  const { invoices } = useInvoices();
  const { deductions, fetchDeductions } = useDeductions();

  useEffect(() => {
    fetchDeductions(year);
  }, [year, fetchDeductions]);

  const deductionsForYear = useMemo(() => deductions.filter((d) => Number(d.tax_year) === year), [deductions, year]);
  const {
    revenue,
    byType,
    adjustedIncome,
    chargeableIncome,
    incomeTax,
    incomeTaxBreakdown,
  } = useTaxCalculation(invoices, deductions, year);

  const businessDeductions = useMemo(() => deductionsForYear.filter((d) => d.category_type === 'business'), [deductionsForYear]);
  const capitalDeductions = useMemo(() => deductionsForYear.filter((d) => d.category_type === 'capital'), [deductionsForYear]);
  const personalDeductions = useMemo(() => deductionsForYear.filter((d) => d.category_type === 'personal'), [deductionsForYear]);

  const totalDeductions = (byType?.business || 0) + (byType?.capital || 0) + (byType?.personal || 0);
  const missingReceipts = useMemo(() => deductionsForYear.filter((d) => !d.has_receipt), [deductionsForYear]);

  const handleDownloadReport = () => {
    let report = `TAX FILING SUMMARY ${year}\n${'='.repeat(50)}\n\n`;
    report += `INCOME\nTotal Revenue: ${formatCurrency(revenue)}\n\n`;
    report += `DEDUCTIONS\nBusiness: ${formatCurrency(byType?.business || 0)}\nCapital: ${formatCurrency(byType?.capital || 0)}\nPersonal: ${formatCurrency(byType?.personal || 0)}\nTotal: ${formatCurrency(totalDeductions)}\n\n`;
    report += `Adjusted Income: ${formatCurrency(adjustedIncome)}\nChargeable Income: ${formatCurrency(chargeableIncome)}\n\n`;
    report += `TAX CALCULATION\nIncome Tax: ${formatCurrency(incomeTax)}\n\n`;
    report += `Generated by CukaiPro\n`;
    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `filing-summary-${year}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportCSV = () => {
    const headers = 'Category,Amount,Claimable,Date,Status\n';
    const rows = deductionsForYear.map((d) => `${d.category_name},${d.amount},${d.claimable_amount},${d.deduction_date},${d.status}`).join('\n');
    const blob = new Blob([headers + rows], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `deductions-${year}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-background-light dark:bg-background-dark min-h-screen flex">
      <Sidebar />
      <main className="ml-64 flex-1 p-8">
        <div className="max-w-7xl mx-auto px-6 py-8">
          <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Tax Filing Summary {year}</h1>
              <p className="text-sm text-slate-500 dark:text-slate-400">Complete report for tax filing</p>
            </div>
            <div className="flex items-center gap-3">
              <select
                value={year}
                onChange={(e) => setYear(Number(e.target.value))}
                className="px-4 py-2.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-custom text-slate-900 dark:text-white"
              >
                {YEARS.map((y) => (
                  <option key={y} value={y}>{y}</option>
                ))}
              </select>
              <button type="button" onClick={handleDownloadReport} className="px-4 py-2.5 rounded-lg bg-primary text-white text-sm font-medium hover:bg-primary/90">
                Download PDF
              </button>
              <button type="button" onClick={handleExportCSV} className="px-4 py-2.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-custom text-sm font-medium hover:bg-slate-50 dark:hover:bg-slate-800/30">
                Export to Excel
              </button>
            </div>
          </div>

          {/* Income summary */}
          <div className="bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-6 mb-8">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-4">Income Summary</h2>
            <p className="text-xl font-bold text-primary dark:text-emerald-400">Total Revenue: {formatCurrency(revenue)}</p>
            <p className="text-sm text-slate-500 dark:text-slate-400 mt-2">By month breakdown and by client available in full report.</p>
          </div>

          {/* Deductions breakdown */}
          <div className="bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-6 mb-8">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-4">Deductions Breakdown</h2>
            <div className="space-y-6">
              <div>
                <h3 className="font-semibold text-slate-800 dark:text-slate-200 mb-2">A) Business Expenses (100% claimable)</h3>
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-left text-slate-500 dark:text-slate-400 border-b border-slate-200 dark:border-slate-700">
                      <th className="py-2">Category</th>
                      <th className="py-2 text-right">Total Amount</th>
                      <th className="py-2 text-right">Claimable</th>
                      <th className="py-2 text-right">Receipts</th>
                    </tr>
                  </thead>
                  <tbody>
                    {businessDeductions.length === 0 ? (
                      <tr><td colSpan={4} className="py-4 text-slate-500">No business deductions</td></tr>
                    ) : (
                      businessDeductions.map((d) => (
                        <tr key={d.id} className="border-b border-slate-100 dark:border-slate-700/50">
                          <td className="py-2">{d.category_name}</td>
                          <td className="py-2 text-right">{formatCurrency(Number(d.amount) || 0)}</td>
                          <td className="py-2 text-right">{formatCurrency(Number(d.claimable_amount) || 0)}</td>
                          <td className="py-2 text-right">{d.has_receipt ? 'Yes' : 'No'}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
                <p className="text-sm font-semibold mt-2 text-right">Subtotal: {formatCurrency(byType?.business || 0)}</p>
              </div>
              <div>
                <h3 className="font-semibold text-slate-800 dark:text-slate-200 mb-2">B) Capital Allowance</h3>
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-left text-slate-500 dark:text-slate-400 border-b border-slate-200 dark:border-slate-700">
                      <th className="py-2">Asset</th>
                      <th className="py-2 text-right">Cost</th>
                      <th className="py-2 text-right">Claimable</th>
                    </tr>
                  </thead>
                  <tbody>
                    {capitalDeductions.length === 0 ? (
                      <tr><td colSpan={3} className="py-4 text-slate-500">No capital allowance</td></tr>
                    ) : (
                      capitalDeductions.map((d) => (
                        <tr key={d.id} className="border-b border-slate-100 dark:border-slate-700/50">
                          <td className="py-2">{d.category_name}</td>
                          <td className="py-2 text-right">{formatCurrency(Number(d.amount) || 0)}</td>
                          <td className="py-2 text-right">{formatCurrency(Number(d.claimable_amount) || 0)}</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
                <p className="text-sm font-semibold mt-2 text-right">Subtotal: {formatCurrency(byType?.capital || 0)}</p>
              </div>
              <div>
                <h3 className="font-semibold text-slate-800 dark:text-slate-200 mb-2">C) Personal Relief</h3>
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-left text-slate-500 dark:text-slate-400 border-b border-slate-200 dark:border-slate-700">
                      <th className="py-2">Category</th>
                      <th className="py-2 text-right">Amount Claimed</th>
                      <th className="py-2">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {personalDeductions.length === 0 ? (
                      <tr><td colSpan={3} className="py-4 text-slate-500">No personal relief</td></tr>
                    ) : (
                      personalDeductions.map((d) => (
                        <tr key={d.id} className="border-b border-slate-100 dark:border-slate-700/50">
                          <td className="py-2">{d.category_name}</td>
                          <td className="py-2 text-right">{formatCurrency(Number(d.claimable_amount) || 0)}</td>
                          <td className="py-2">✓ within limit</td>
                        </tr>
                      ))
                    )}
                  </tbody>
                </table>
                <p className="text-sm font-semibold mt-2 text-right">Subtotal: {formatCurrency(byType?.personal || 0)}</p>
              </div>
            </div>
            <p className="text-lg font-bold mt-4 pt-4 border-t border-slate-200 dark:border-slate-700">TOTAL DEDUCTIONS: {formatCurrency(totalDeductions)}</p>
          </div>

          {/* Tax calculation */}
          <div className="bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-6 mb-8">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-4">Tax Calculation</h2>
            <div className="space-y-2 text-sm mb-4">
              <p>Gross Business Income: {formatCurrency(revenue)}</p>
              <p>Less: Business Expenses: -{formatCurrency(byType?.business || 0)}</p>
              <p>Less: Capital Allowance: -{formatCurrency(byType?.capital || 0)}</p>
              <p className="font-semibold">Adjusted Income: {formatCurrency(adjustedIncome)}</p>
              <p>Less: Personal Relief: -{formatCurrency(byType?.personal || 0)}</p>
              <p className="font-semibold">Chargeable Income: {formatCurrency(chargeableIncome)}</p>
            </div>
            <h3 className="font-semibold text-slate-800 dark:text-slate-200 mb-2">Progressive Rates</h3>
            <ul className="space-y-1 text-sm mb-4">
              {incomeTaxBreakdown.map((row, i) => (
                <li key={i}>{row.band} @ {row.rate}%: {formatCurrency(row.tax)}</li>
              ))}
            </ul>
            <p className="text-lg font-bold text-slate-900 dark:text-white">TOTAL TAX PAYABLE: {formatCurrency(incomeTax)}</p>
          </div>

          {/* Missing receipts */}
          {missingReceipts.length > 0 && (
            <div className="bg-amber-50 dark:bg-amber-900/20 rounded-xl border border-amber-200 dark:border-amber-800 p-6 mb-8">
              <h2 className="text-lg font-bold text-amber-800 dark:text-amber-200 mb-2">⚠️ Missing Receipts</h2>
              <p className="text-sm text-amber-700 dark:text-amber-300 mb-4">Upload receipts before filing. The following deductions have no receipt:</p>
              <ul className="list-disc list-inside text-sm text-slate-700 dark:text-slate-300">
                {missingReceipts.slice(0, 10).map((d) => (
                  <li key={d.id}>{d.category_name} - {formatCurrency(Number(d.amount) || 0)} ({d.deduction_date})</li>
                ))}
                {missingReceipts.length > 10 && <li>...and {missingReceipts.length - 10} more</li>}
              </ul>
            </div>
          )}

          <div className="flex gap-3">
            <button type="button" onClick={handleDownloadReport} className="px-4 py-2.5 rounded-lg bg-primary text-white font-medium hover:bg-primary/90">
              Download Filing Report
            </button>
            <button type="button" onClick={handleExportCSV} className="px-4 py-2.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-custom font-medium hover:bg-slate-50 dark:hover:bg-slate-800/30">
              Export to CSV
            </button>
            <button type="button" onClick={() => window.print()} className="px-4 py-2.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-custom font-medium hover:bg-slate-50 dark:hover:bg-slate-800/30">
              Print Summary
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}

export default FilingSummaryPage;
