import { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import Sidebar from '../../components/Sidebar';
import { useInvoices } from '../../hooks/useInvoices';
import { useDeductions } from '../../hooks/useDeductions';
import { useTaxCalculation } from '../../hooks/useTaxCalculation';
import { useSstFilings } from '../../hooks/useSstFilings';
import { formatCurrency } from '../../utils/validators';

const currentYear = new Date().getFullYear();
const INCOME_TAX_DEADLINE = '30 June 2024';

function TaxesPage() {
  const navigate = useNavigate();
  const [taxYear, setTaxYear] = useState(currentYear);
  const { invoices } = useInvoices();
  const { nextDueDate, daysUntilNextDue, nextFilingPeriod } = useSstFilings();
  const { deductions, fetchDeductions } = useDeductions();

  useEffect(() => {
    fetchDeductions(taxYear);
  }, [taxYear, fetchDeductions]);

  const {
    sstPayable,
    revenue,
    totalDeductions,
    byType,
    adjustedIncome,
    chargeableIncome,
    incomeTax,
  } = useTaxCalculation(invoices, deductions, taxYear);

  const totalLiability = sstPayable + incomeTax;

  const filingHistory = [
    { period: 'May 2024', amount: 0, status: 'pending', dateFiled: '—' },
    { period: 'April 2024', amount: 0, status: 'filed', dateFiled: '15 May 2024' },
  ];

  const handleDownloadReport = () => {
    const content = `TAX REPORT ${taxYear}\n${'='.repeat(40)}\n\nSST Payable: ${formatCurrency(sstPayable)}\nIncome Tax (Est.): ${formatCurrency(incomeTax)}\nTotal Liability: ${formatCurrency(totalLiability)}\n\nGenerated by CukaiPro`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `tax-report-${taxYear}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleFileSST = () => {
    navigate('/dashboard/sst-filing');
  };

  const sstDeadlineStr =
    nextDueDate
      ? `${nextDueDate.getDate()} ${nextDueDate.toLocaleString('en-MY', { month: 'long' })} ${nextDueDate.getFullYear()}`
      : nextFilingPeriod?.dueDateStr || '15th of each month';

  return (
    <div className="bg-background-light dark:bg-background-dark min-h-screen flex">
      <Sidebar />
      <main className="ml-64 flex-1 p-8">
        <div className="max-w-7xl mx-auto px-6 py-8">
          <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Tax Management</h1>
              <p className="text-sm text-slate-500 dark:text-slate-400">Manage your SST and Income Tax filings</p>
            </div>
            <div className="flex gap-3">
              <Link
                to="/dashboard/sst-filing"
                className="flex items-center gap-2 bg-white dark:bg-slate-custom border border-slate-200 dark:border-slate-700 px-4 py-2.5 rounded-lg text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-800/30 font-medium text-sm"
              >
                SST Filing
              </Link>
              <Link
                to="/dashboard/deductions"
                className="flex items-center gap-2 bg-white dark:bg-slate-custom border border-slate-200 dark:border-slate-700 px-4 py-2.5 rounded-lg text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-800/30 font-medium text-sm"
              >
                View Deductions
              </Link>
              <button
                type="button"
                onClick={handleDownloadReport}
                className="flex items-center gap-2 bg-primary text-white px-4 py-2.5 rounded-lg hover:bg-primary/90 font-medium text-sm"
              >
                Download Tax Report
              </button>
            </div>
          </div>

          {/* Summary cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
            <div className="bg-amber-50 dark:bg-amber-900/20 rounded-xl border border-amber-200 dark:border-amber-800 p-6">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-lg bg-amber-500/20 text-amber-600 dark:text-amber-400 flex items-center justify-center">
                  <span className="material-icons">account_balance</span>
                </div>
                <div>
                  <p className="text-xs font-semibold text-amber-800 dark:text-amber-300 uppercase">Total Tax Liability</p>
                  <p className="text-xl font-bold text-slate-900 dark:text-white">{formatCurrency(totalLiability)}</p>
                  <p className="text-xs text-slate-500 dark:text-slate-400">For year {taxYear}</p>
                </div>
              </div>
            </div>
            <div className="bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 p-6 shadow-sm">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-lg bg-blue-500/10 text-blue-500 flex items-center justify-center">
                  <span className="material-icons">receipt</span>
                </div>
                <div>
                  <p className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase">SST Payable</p>
                  <p className="text-xl font-bold text-slate-900 dark:text-white">{formatCurrency(sstPayable)}</p>
                  <p className="text-xs text-slate-500 dark:text-slate-400">Sales & Service Tax</p>
                  <button type="button" onClick={handleFileSST} className="mt-2 text-sm font-medium text-primary dark:text-emerald-400 hover:underline">File SST-02</button>
                </div>
              </div>
            </div>
            <div className="bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 p-6 shadow-sm">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-lg bg-purple-500/10 text-purple-500 flex items-center justify-center">
                  <span className="material-icons">calculate</span>
                </div>
                <div>
                  <p className="text-xs font-semibold text-slate-500 dark:text-slate-400 uppercase">Income Tax (Estimated)</p>
                  <p className="text-xl font-bold text-slate-900 dark:text-white">{formatCurrency(incomeTax)}</p>
                  <p className="text-xs text-slate-500 dark:text-slate-400">Estimated liability</p>
                  <button type="button" className="mt-2 text-sm font-medium text-primary dark:text-emerald-400 hover:underline">View Breakdown</button>
                </div>
              </div>
            </div>
          </div>

          {/* SST Filing */}
          <div className="bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-6 mb-8">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-4">SST-02 Filing</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
              <div>
                <p className="text-sm text-slate-500 dark:text-slate-400">Next deadline</p>
                <p className="font-bold text-slate-900 dark:text-white">{sstDeadlineStr}</p>
                {daysUntilNextDue != null && (
                  <p
                    className={`text-xs ${
                      daysUntilNextDue < 0
                        ? 'text-red-600 dark:text-red-400'
                        : daysUntilNextDue <= 7
                        ? 'text-amber-600 dark:text-amber-400'
                        : 'text-slate-500 dark:text-slate-400'
                    }`}
                  >
                    {daysUntilNextDue < 0
                      ? 'Overdue'
                      : daysUntilNextDue === 0
                      ? 'Due today'
                      : `${daysUntilNextDue} days left`}
                  </p>
                )}
              </div>
              <div>
                <p className="text-sm text-slate-500 dark:text-slate-400">Status</p>
                <span className="inline-flex px-2.5 py-0.5 rounded-full text-xs font-medium bg-amber-500/10 text-amber-600 dark:text-amber-400">Pending</span>
              </div>
            </div>
            <p className="text-sm text-slate-600 dark:text-slate-400 mb-4">SST collected this month: {formatCurrency(0)} • YTD: {formatCurrency(sstPayable)}</p>
            <div className="flex gap-3 mb-6">
              <button type="button" onClick={handleDownloadReport} className="px-4 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 text-sm font-medium hover:bg-slate-50 dark:hover:bg-slate-700">Download SST Report</button>
              <button type="button" onClick={handleFileSST} className="px-4 py-2 rounded-lg bg-primary text-white text-sm font-medium hover:bg-primary/90">File SST-02</button>
            </div>
            <h3 className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">Filing History (last 6)</h3>
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-slate-500 dark:text-slate-400 border-b border-slate-200 dark:border-slate-700">
                  <th className="py-2">Filing Period</th>
                  <th className="py-2">Amount Filed</th>
                  <th className="py-2">Status</th>
                  <th className="py-2">Date Filed</th>
                </tr>
              </thead>
              <tbody>
                {filingHistory.map((row, i) => (
                  <tr key={i} className="border-b border-slate-100 dark:border-slate-700/50">
                    <td className="py-2">{row.period}</td>
                    <td className="py-2">{formatCurrency(row.amount)}</td>
                    <td className="py-2">{row.status === 'filed' ? 'Filed ✓' : 'Overdue ✗'}</td>
                    <td className="py-2">{row.dateFiled}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Income Tax + Deductions summary */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
            <div className="bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-6">
              <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-4">Income Tax Filing</h2>
              <p className="text-sm text-slate-500 dark:text-slate-400 mb-2">Form type: Form B / Form C • Tax year: 2023 • Deadline: {INCOME_TAX_DEADLINE}</p>
              <p className="text-sm mb-4">Status: <span className="text-amber-600 dark:text-amber-400 font-medium">Not Filed</span></p>
              <div className="space-y-2 text-sm">
                <p>Gross Business Income: {formatCurrency(revenue)}</p>
                <p>Less: Business Deductions: {formatCurrency(byType?.business || 0)}</p>
                <p>Less: Capital Allowance: {formatCurrency(byType?.capital || 0)}</p>
                <p>Less: Personal Relief: {formatCurrency(byType?.personal || 0)}</p>
                <p className="font-semibold pt-2">Chargeable Income: {formatCurrency(chargeableIncome)}</p>
              </div>
            </div>
            <div className="bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-6">
              <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-4">Tax Deductions Summary</h2>
              <div className="space-y-2 text-sm mb-4">
                <p>Business Expenses: {formatCurrency(byType?.business || 0)}</p>
                <p>Capital Allowance: {formatCurrency(byType?.capital || 0)}</p>
                <p>Personal Relief: {formatCurrency(byType?.personal || 0)}</p>
              </div>
              <Link to="/dashboard/deductions" className="text-primary dark:text-emerald-400 font-medium text-sm hover:underline">View All Deductions</Link>
            </div>
          </div>

          {/* Tax calendar */}
          <div className="bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-6">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-4">Tax Calendar</h2>
            <ul className="space-y-2 text-sm">
              <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-emerald-500"></span> SST-02: 15th of each month</li>
              <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-amber-500"></span> Income Tax (Form B/C): 30 June</li>
              <li className="flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-slate-400"></span> CP204 estimates: 15 Mar, 30 Jun, 30 Sep, 15 Dec</li>
            </ul>
          </div>
        </div>
      </main>
    </div>
  );
}

export default TaxesPage;
