import { useMemo, useState, useRef, useCallback } from 'react';
import { Link } from 'react-router-dom';
import Sidebar from '../../components/Sidebar';
import { useInvoices } from '../../hooks/useInvoices';
import { formatCurrency, formatDate } from '../../utils/validators';
import PaymentModal from './PaymentModal';
import SupportChatModal from './SupportChatModal';

const MAX_FILE_SIZE_MB = 10;
const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;

const EXPENSE_ICON_COLORS = [
  'bg-blue-500/10 text-blue-500',
  'bg-purple-500/10 text-purple-500',
  'bg-orange-500/10 text-orange-500',
  'bg-emerald-500/10 text-emerald-500',
  'bg-amber-500/10 text-amber-500',
];

/** Icon color from first letter of client name. */
function getIconColorClass(name) {
  if (!name || !name.length) return EXPENSE_ICON_COLORS[0];
  const i = (name.charCodeAt(0) || 0) % EXPENSE_ICON_COLORS.length;
  return EXPENSE_ICON_COLORS[i];
}

/** LHDN status badge: pending→amber, validated→emerald, submitted→blue, draft→slate. */
function getStatusBadgeClass(status) {
  const s = (status || 'draft').toLowerCase();
  if (s === 'pending') return 'bg-amber-500/10 text-amber-500';
  if (s === 'validated' || s === 'paid') return 'bg-emerald-500/10 text-emerald-500';
  if (s === 'submitted' || s === 'sent') return 'bg-blue-500/10 text-blue-500';
  return 'bg-slate-500/10 text-slate-500 dark:bg-slate-400/10 text-slate-400';
}

function getStatusLabel(status) {
  const s = (status || 'draft').toLowerCase();
  if (s === 'pending') return 'Pending';
  if (s === 'validated' || s === 'paid') return 'Verified';
  if (s === 'submitted' || s === 'sent') return 'Submitted';
  return 'Draft';
}

/** Relative time e.g. "2 hours ago". */
function getRelativeTime(isoString) {
  if (!isoString) return '';
  const date = new Date(isoString);
  const now = new Date();
  const sec = Math.floor((now - date) / 1000);
  if (sec < 60) return 'Just now';
  if (sec < 3600) return `${Math.floor(sec / 60)} min ago`;
  if (sec < 86400) return `${Math.floor(sec / 3600)} hours ago`;
  if (sec < 604800) return `${Math.floor(sec / 86400)} days ago`;
  return formatDate(date);
}

/** Parse DD/MM/YYYY for sorting. */
function parseInvoiceDate(d) {
  if (!d) return 0;
  if (typeof d === 'string' && /^\d{2}\/\d{2}\/\d{4}$/.test(d)) {
    const [day, month, year] = d.split('/').map(Number);
    return new Date(year, month - 1, day).getTime();
  }
  return new Date(d).getTime();
}

function Dashboard() {
  const { invoices, loading } = useInvoices();
  const [paymentModalOpen, setPaymentModalOpen] = useState(false);
  const [chatModalOpen, setChatModalOpen] = useState(false);
  const [isUploading, setIsUploading] = useState(false);
  const fileInputRef = useRef(null);

  const totalSst = useMemo(() => {
    return invoices.reduce((sum, inv) => sum + (Number(inv.amount) || 0), 0);
  }, [invoices]);

  const recentExpenses = useMemo(() => {
    return [...invoices]
      .sort((a, b) => parseInvoiceDate(b.invoice_date) - parseInvoiceDate(a.invoice_date))
      .slice(0, 3);
  }, [invoices]);

  const recentActivity = useMemo(() => {
    return invoices.slice(0, 5);
  }, [invoices]);

  const handlePayNow = useCallback(() => {
    console.log('Pay Now clicked');
    setPaymentModalOpen(true);
  }, []);

  const handleDownloadReport = useCallback(() => {
    console.log('Download Report clicked');
    const now = new Date();
    const reportDate = formatDate(now);
    const monthYear = `${now.toLocaleString('en-MY', { month: 'long' })} ${now.getFullYear()}`;
    const filingPeriod = 'May 2024';

    const invoiceDetailLines = invoices.map((inv) => {
      const dateStr = inv.invoice_date
        ? (typeof inv.invoice_date === 'string' && /^\d{2}\/\d{2}\/\d{4}$/.test(inv.invoice_date)
          ? inv.invoice_date
          : formatDate(inv.invoice_date))
        : '—';
      const amount = Number(inv.amount) || 0;
      const status = inv.lhdn_status || inv.status || 'draft';
      return `Invoice #${String(inv.id).slice(0, 8)}
Client: ${inv.client_name || '—'}
Date: ${dateStr}
Amount: RM ${amount.toFixed(2)}
Status: ${status}
---`;
    }).join('\n\n');

    const content = `SST REPORT
==========

Report Date: ${reportDate}
Filing Period: ${filingPeriod}

SUMMARY
-------
Total SST Payable: ${formatCurrency(totalSst)}
Total Invoices: ${invoices.length}

INVOICE DETAILS
---------------
${invoiceDetailLines || '(No invoices)'}

Generated by CukaiPro
`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `sst-report-${now.getMonth() + 1}-${now.getFullYear()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [invoices, totalSst]);

  const handleUploadReceipt = useCallback(() => {
    if (fileInputRef.current) {
      fileInputRef.current.click();
    }
  }, []);

  const handleFileChange = useCallback((e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (file.size > MAX_FILE_SIZE_BYTES) {
      alert(`File too large. Maximum size is ${MAX_FILE_SIZE_MB}MB.`);
      e.target.value = '';
      return;
    }
    setIsUploading(true);
    console.log('File selected for upload:', file.name);
    alert(`File uploaded: ${file.name}`);
    e.target.value = '';
    setTimeout(() => setIsUploading(false), 600);
  }, []);

  const handleOpenChat = useCallback(() => {
    console.log('Open Chat clicked');
    setChatModalOpen(true);
  }, []);

  return (
    <div className="bg-background-light dark:bg-background-dark font-display text-slate-900 dark:text-slate-100 min-h-screen flex">
      <Sidebar />

      {/* Main Content */}
      <main className="ml-64 flex-1 p-8">
        {/* Header */}
        <header className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Dashboard Overview</h1>
            <p className="text-slate-500 dark:text-slate-400 text-sm">Welcome back, here&apos;s your tax status for May 2024.</p>
          </div>
          <div className="flex items-center gap-4">
            <div className="relative">
              <button className="flex items-center gap-2 px-4 py-2 bg-white dark:bg-slate-custom border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-medium">
                <span className="material-icons text-sm">calendar_today</span>
                May 1 - May 31, 2024
              </button>
            </div>
            <button className="p-2 bg-white dark:bg-slate-custom border border-slate-200 dark:border-slate-700 rounded-lg text-slate-500">
              <span className="material-icons">notifications</span>
            </button>
          </div>
        </header>

        {/* Bento Grid */}
        <div className="grid grid-cols-12 gap-6 auto-rows-[160px]">
          {/* Featured Card (Large 2x2 style) */}
          <div className="col-span-12 lg:col-span-8 row-span-2 bg-primary rounded-xl p-8 flex flex-col justify-between relative overflow-hidden border border-white/10 shadow-xl">
            <div className="absolute top-0 right-0 p-8 opacity-10">
              <span className="material-icons text-[120px]">account_balance_wallet</span>
            </div>
            <div className="relative z-10">
              <div className="inline-flex items-center gap-2 px-3 py-1 bg-white/10 rounded-full text-white/80 text-xs font-medium backdrop-blur-sm">
                <span className="w-2 h-2 rounded-full bg-red-400"></span>
                Action Required: SST Filing
              </div>
              <h2 className="text-white/70 mt-6 text-lg font-medium">Total SST Payable</h2>
              {loading ? (
                <div className="text-white/80 text-2xl mt-2">Loading...</div>
              ) : (
                <div className="text-white text-5xl font-bold mt-2 tracking-tight">
                  {formatCurrency(totalSst)}
                </div>
              )}
              <p className="text-white/60 text-sm mt-4 flex items-center gap-2">
                <span className="material-icons text-sm">schedule</span>
                SST-02 Due in 12 days (June 15, 2024)
              </p>
            </div>
            <div className="relative z-10 flex gap-4">
              <button
                type="button"
                onClick={handlePayNow}
                className="bg-white text-primary px-6 py-3 rounded-lg font-bold text-sm hover:bg-slate-100 transition-colors shadow-lg"
              >
                Pay Now
              </button>
              <button
                type="button"
                onClick={handleDownloadReport}
                className="bg-white/10 border border-white/20 text-white px-6 py-3 rounded-lg font-bold text-sm hover:bg-white/20 transition-colors backdrop-blur-sm"
              >
                Download Report
              </button>
            </div>
          </div>

          {/* Secondary Card (Medium 4x1) */}
          <div className="col-span-12 lg:col-span-4 row-span-2 bg-slate-custom rounded-xl p-6 border border-slate-700 shadow-lg flex flex-col justify-between">
            <div>
              <div className="flex items-center justify-between mb-6">
                <h3 className="text-white font-semibold">Next LHDN Deadline</h3>
                <span className="material-icons text-slate-400">event</span>
              </div>
              <div className="flex items-center justify-center py-4">
                <div className="text-center">
                  <div className="text-5xl font-bold text-white mb-1">14</div>
                  <div className="text-slate-400 text-xs uppercase tracking-widest font-bold">Days Left</div>
                </div>
              </div>
            </div>
            <div className="space-y-4">
              <div className="bg-slate-800/50 p-4 rounded-lg border border-slate-700">
                <div className="flex justify-between items-center mb-1">
                  <span className="text-white font-medium text-sm">Form C</span>
                  <span className="text-xs font-bold text-emerald-400">35% Ready</span>
                </div>
                <div className="w-full bg-slate-700 h-1.5 rounded-full overflow-hidden">
                  <div className="bg-emerald-500 h-full w-[35%]"></div>
                </div>
              </div>
              <div className="flex justify-between text-xs text-slate-400">
                <span>Filing Period: 2023</span>
                <span className="text-white">Due: 30 June 2024</span>
              </div>
            </div>
          </div>

          {/* Recent Expenses (Medium-Wide) */}
          <div className="col-span-12 lg:col-span-7 row-span-2 bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm flex flex-col overflow-hidden">
            <div className="p-6 border-b border-slate-200 dark:border-slate-700 flex justify-between items-center">
              <h3 className="font-bold dark:text-white">Recent Tax-Deductible Expenses</h3>
              <Link
                to="/dashboard/invoices"
                className="text-primary dark:text-emerald-400 text-xs font-bold hover:underline"
              >
                View All
              </Link>
            </div>
            <div className="flex-1 overflow-y-auto">
              <div className="divide-y divide-slate-200 dark:divide-slate-700/50">
                {loading && recentExpenses.length === 0 ? (
                  <div className="p-6 text-center text-sm text-slate-500 dark:text-slate-400">
                    Loading...
                  </div>
                ) : recentExpenses.length === 0 ? (
                  <div className="p-6 text-center text-sm text-slate-500 dark:text-slate-400">
                    No invoices yet
                  </div>
                ) : (
                  recentExpenses.map((invoice) => {
                    const dateStr = invoice.invoice_date
                      ? (typeof invoice.invoice_date === 'string' && /^\d{2}\/\d{2}\/\d{4}$/.test(invoice.invoice_date)
                        ? invoice.invoice_date
                        : formatDate(invoice.invoice_date))
                      : '—';
                    const amount = Number(invoice.amount) || 0;
                    const amountFormatted = amount > 0 ? `-${formatCurrency(amount)}` : formatCurrency(0);
                    const status = invoice.lhdn_status || invoice.status;
                    return (
                      <div
                        key={invoice.id}
                        className="p-4 flex items-center gap-4 hover:bg-slate-50 dark:hover:bg-slate-800/30 transition-colors"
                      >
                        <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${getIconColorClass(invoice.client_name)}`}>
                          <span className="material-icons text-xl">description</span>
                        </div>
                        <div className="flex-1">
                          <p className="text-sm font-semibold dark:text-white">
                            {invoice.client_name || 'Unknown Client'}
                          </p>
                          <p className="text-xs text-slate-500 dark:text-slate-400">
                            Invoice • {dateStr}
                          </p>
                        </div>
                        <div className="text-right">
                          <p className="text-sm font-bold dark:text-white">{amountFormatted}</p>
                          <span className={`inline-flex px-2 py-0.5 rounded text-[10px] font-bold ${getStatusBadgeClass(status)}`}>
                            {getStatusLabel(status)}
                          </span>
                        </div>
                      </div>
                    );
                  })
                )}
              </div>
            </div>
          </div>

          {/* Staff Activity (Small-Square style) */}
          <div className="col-span-12 lg:col-span-5 row-span-2 bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm flex flex-col">
            <div className="p-6 border-b border-slate-200 dark:border-slate-700">
              <h3 className="font-bold dark:text-white">Staff Activity</h3>
            </div>
            <div className="flex-1 p-6 space-y-6 overflow-y-auto">
              {loading && recentActivity.length === 0 ? (
                <div className="text-sm text-slate-500 dark:text-slate-400">Loading...</div>
              ) : recentActivity.length === 0 ? (
                <div className="text-sm text-slate-500 dark:text-slate-400">No recent activity</div>
              ) : (
                recentActivity.map((invoice) => (
                  <div key={invoice.id} className="flex gap-4">
                    <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center shrink-0">
                      <span className="material-icons text-primary dark:text-emerald-400 text-sm">description</span>
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="text-xs text-slate-500 dark:text-slate-400 mb-1">
                        {getRelativeTime(invoice.created_at)}
                      </p>
                      <p className="text-sm dark:text-slate-200 leading-tight">
                        Invoice created for <span className="text-primary dark:text-emerald-400 font-medium">{invoice.client_name || 'Unknown Client'}</span>.
                      </p>
                    </div>
                  </div>
                ))
              )}
            </div>
            <div className="p-4 bg-slate-50 dark:bg-slate-800/50 text-center rounded-b-xl">
              <Link
                to="/dashboard/invoices"
                className="text-xs font-bold text-slate-500 hover:text-primary transition-colors"
              >
                Show Full Audit Log
              </Link>
            </div>
          </div>

          {/* Mini Widget: Upload Quick Action */}
          <div
            role="button"
            tabIndex={0}
            onClick={handleUploadReceipt}
            onKeyDown={(e) => e.key === 'Enter' && handleUploadReceipt()}
            className={`col-span-12 lg:col-span-4 row-span-1 bg-white dark:bg-slate-custom rounded-xl border-2 border-dashed flex flex-col items-center justify-center p-6 cursor-pointer transition-colors group focus:outline-none focus:ring-2 focus:ring-primary/50 ${
              isUploading
                ? 'border-primary dark:border-emerald-500'
                : 'border-slate-200 dark:border-slate-700 hover:border-primary dark:hover:border-emerald-500'
            }`}
          >
            <input
              ref={fileInputRef}
              type="file"
              accept=".pdf,.jpg,.jpeg,.png"
              className="hidden"
              onChange={handleFileChange}
              aria-label="Upload receipt"
            />
            <span className="material-icons text-slate-400 group-hover:text-primary transition-colors text-3xl mb-2">cloud_upload</span>
            <span className="font-bold text-sm dark:text-white">Quick Upload Receipt</span>
            <span className="text-xs text-slate-500">PDF, JPG or PNG up to 10MB</span>
          </div>

          {/* Mini Widget: Support */}
          <div className="col-span-12 lg:col-span-4 row-span-1 bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 p-6 flex items-center gap-4">
            <div className="w-12 h-12 bg-amber-500/10 text-amber-500 rounded-lg flex items-center justify-center">
              <span className="material-icons">support_agent</span>
            </div>
            <div>
              <h4 className="font-bold text-sm dark:text-white">Tax Expert Support</h4>
              <p className="text-xs text-slate-500">Speak to an advisor now</p>
              <button
                type="button"
                onClick={handleOpenChat}
                className="mt-2 text-primary dark:text-emerald-400 text-xs font-bold hover:underline"
              >
                Open Chat
              </button>
            </div>
          </div>

          {/* Mini Widget: Tax Savings */}
          <div className="col-span-12 lg:col-span-4 row-span-1 bg-emerald-500/10 rounded-xl border border-emerald-500/20 p-6 flex items-center gap-4">
            <div className="w-12 h-12 bg-emerald-500/20 text-emerald-500 rounded-lg flex items-center justify-center">
              <span className="material-icons">savings</span>
            </div>
            <div>
              <h4 className="font-bold text-sm dark:text-emerald-400">Projected Savings</h4>
              <div className="text-xl font-bold dark:text-white">RM 2,840.50</div>
              <p className="text-[10px] text-slate-500 uppercase tracking-wider font-bold">Optimized for 2024</p>
            </div>
          </div>
        </div>

        <PaymentModal
          isOpen={paymentModalOpen}
          onClose={() => setPaymentModalOpen(false)}
          totalAmount={totalSst}
        />
        <SupportChatModal
          isOpen={chatModalOpen}
          onClose={() => setChatModalOpen(false)}
        />
      </main>
    </div>
  );
}

export default Dashboard;
