import { useMemo } from 'react';
import { formatCurrency } from '../utils/validators';
import { getCategoryById } from '../data/taxCategories';

/**
 * Malaysian individual income tax progressive rates (annual chargeable income).
 * First RM 5,000 @ 0%, next 15k @ 1%, 15k @ 3%, 15k @ 6%, 20k @ 11%, 30k @ 19%, 50k @ 25%, 50k @ 26%, 100k @ 28%, above @ 30%.
 */
const PROGRESSIVE_BRACKETS = [
  { limit: 5000, rate: 0 },
  { limit: 15000, rate: 0.01 },
  { limit: 15000, rate: 0.03 },
  { limit: 15000, rate: 0.06 },
  { limit: 20000, rate: 0.11 },
  { limit: 30000, rate: 0.19 },
  { limit: 50000, rate: 0.25 },
  { limit: 50000, rate: 0.26 },
  { limit: 100000, rate: 0.28 },
  { limit: Infinity, rate: 0.3 },
];

/**
 * Calculate total claimable deductions from deductions array.
 * @param {Array} deductions - List of deduction objects with claimable_amount or amount + claimable_percentage
 * @returns {{ total: number, byType: { business: number, capital: number, personal: number } }}
 */
export function calculateTotalDeductions(deductions) {
  const byType = { business: 0, capital: 0, personal: 0 };
  let total = 0;
  (deductions || []).forEach((d) => {
    const amt = Number(d.claimable_amount ?? (d.amount || 0) * ((d.claimable_percentage || 0) / 100)) || 0;
    total += amt;
    const t = d.category_type || 'business';
    if (byType[t] != null) byType[t] += amt;
  });
  return { total, byType };
}

/**
 * SST at 6% on taxable value (invoices amount).
 * @param {Array} invoices - Invoices with amount
 * @returns {number}
 */
export function calculateSSTPayable(invoices) {
  return (invoices || []).reduce((sum, inv) => sum + (Number(inv.amount) || 0), 0) * 0.06;
}

/**
 * Calculate income tax using Malaysian progressive rates.
 * @param {number} chargeableIncome - Chargeable income (after deductions)
 * @returns {{ tax: number, breakdown: Array<{ band: string, amount: number, tax: number }> }}
 */
export function calculateIncomeTax(chargeableIncome) {
  if (chargeableIncome <= 0) return { tax: 0, breakdown: [] };
  let remaining = chargeableIncome;
  let tax = 0;
  const breakdown = [];
  let prevLimit = 0;
  PROGRESSIVE_BRACKETS.forEach(({ limit, rate }) => {
    const bandSize = limit === Infinity ? Math.max(0, remaining) : Math.min(limit, remaining);
    if (bandSize <= 0) return;
    const bandTax = bandSize * rate;
    tax += bandTax;
    const bandLabel = limit === Infinity ? `Above RM ${prevLimit.toLocaleString()}` : `RM ${prevLimit.toLocaleString()} - ${(prevLimit + limit).toLocaleString()}`;
    breakdown.push({ band: bandLabel, amount: bandSize, rate: rate * 100, tax: bandTax });
    remaining -= bandSize;
    prevLimit += limit === Infinity ? bandSize : limit;
  });
  return { tax, breakdown };
}

/**
 * Estimate tax savings from deductions at 24% average rate.
 * @param {Array} deductions
 * @returns {number}
 */
export function estimateTaxSavings(deductions) {
  const { total } = calculateTotalDeductions(deductions);
  return total * 0.24;
}

/**
 * Generate a text filing report for a year.
 * @param {Array} invoices
 * @param {Array} deductions
 * @param {number} year
 * @returns {string}
 */
export function generateFilingReport(invoices, deductions, year) {
  const revenue = (invoices || []).reduce((s, i) => s + (Number(i.amount) || 0), 0);
  const { total: totalDeductions, byType } = calculateTotalDeductions(deductions);
  const adjustedIncome = Math.max(0, revenue - (byType.business || 0) - (byType.capital || 0));
  const chargeableIncome = Math.max(0, adjustedIncome - (byType.personal || 0));
  const { tax } = calculateIncomeTax(chargeableIncome);
  const sst = calculateSSTPayable(invoices || []);

  let report = `TAX FILING REPORT ${year}\n`;
  report += `${'='.repeat(50)}\n\n`;
  report += `INCOME\nGross Revenue: ${formatCurrency(revenue)}\n\n`;
  report += `DEDUCTIONS\nBusiness: ${formatCurrency(byType.business || 0)}\nCapital: ${formatCurrency(byType.capital || 0)}\nPersonal: ${formatCurrency(byType.personal || 0)}\nTotal: ${formatCurrency(totalDeductions)}\n\n`;
  report += `Adjusted Income: ${formatCurrency(adjustedIncome)}\n`;
  report += `Chargeable Income: ${formatCurrency(chargeableIncome)}\n\n`;
  report += `INCOME TAX (Estimated): ${formatCurrency(tax)}\n`;
  report += `SST Payable: ${formatCurrency(sst)}\n`;
  report += `\nGenerated by CukaiPro\n`;
  return report;
}

/**
 * Hook: compute common tax metrics from invoices and deductions.
 */
export function useTaxCalculation(invoices, deductions, taxYear) {
  const deductionsForYear = useMemo(
    () => (deductions || []).filter((d) => Number(d.tax_year) === Number(taxYear)),
    [deductions, taxYear]
  );
  const invoicesForYear = useMemo(() => {
    if (!invoices?.length) return [];
    return invoices.filter((inv) => {
      const d = inv.invoice_date;
      if (!d) return false;
      const y = typeof d === 'string' && /^\d{2}\/\d{2}\/\d{4}$/.test(d)
        ? parseInt(d.split('/')[2], 10)
        : new Date(d).getFullYear();
      return y === Number(taxYear);
    });
  }, [invoices, taxYear]);

  const totalDeductions = useMemo(() => calculateTotalDeductions(deductionsForYear), [deductionsForYear]);
  const sstPayable = useMemo(() => calculateSSTPayable(invoicesForYear), [invoicesForYear]);
  const revenue = useMemo(
    () => invoicesForYear.reduce((s, i) => s + (Number(i.amount) || 0), 0),
    [invoicesForYear]
  );
  const adjustedIncome = useMemo(
    () => Math.max(0, revenue - (totalDeductions.byType.business || 0) - (totalDeductions.byType.capital || 0)),
    [revenue, totalDeductions]
  );
  const chargeableIncome = useMemo(
    () => Math.max(0, adjustedIncome - (totalDeductions.byType.personal || 0)),
    [adjustedIncome, totalDeductions]
  );
  const incomeTaxResult = useMemo(() => calculateIncomeTax(chargeableIncome), [chargeableIncome]);
  const taxSavings = useMemo(() => estimateTaxSavings(deductionsForYear), [deductionsForYear]);

  return {
    deductionsForYear,
    invoicesForYear,
    totalDeductions: totalDeductions.total,
    byType: totalDeductions.byType,
    sstPayable,
    revenue,
    adjustedIncome,
    chargeableIncome,
    incomeTax: incomeTaxResult.tax,
    incomeTaxBreakdown: incomeTaxResult.breakdown,
    taxSavings,
  };
}
