import { useState, useMemo, useEffect, useCallback } from 'react';
import { Link } from 'react-router-dom';
import Sidebar from '../../components/Sidebar';
import ReportsSkeleton from '../../components/Common/ReportsSkeleton';
import { useInvoices } from '../../hooks/useInvoices';
import { useDeductions } from '../../hooks/useDeductions';
import { useTaxCalculation } from '../../hooks/useTaxCalculation';
import { useOrganization } from '../../context/OrganizationContext';
import { formatCurrency, formatDate } from '../../utils/validators';

const currentYearForList = new Date().getFullYear();
const YEARS = Array.from({ length: 5 }, (_, i) => currentYearForList - i);

function ReportsPage() {
  const { currentOrganization } = useOrganization();
  const [year, setYear] = useState(currentYearForList);
  const { invoices, loading: invoicesLoading } = useInvoices();
  const { deductions, fetchDeductions, loading: deductionsLoading } = useDeductions();

  useEffect(() => {
    fetchDeductions(year);
  }, [year, fetchDeductions]);

  const deductionsForYear = useMemo(
    () => deductions.filter((d) => Number(d.tax_year) === year),
    [deductions, year]
  );

  const {
    revenue,
    byType,
    adjustedIncome,
    chargeableIncome,
    incomeTax,
    incomeTaxBreakdown,
  } = useTaxCalculation(invoices, deductions, year);

  const totalSst = useMemo(() => {
    return invoices.reduce((sum, inv) => {
      const amt = Number(inv.amount) || 0;
      const rate = Number(inv.sst_rate) || 0.1;
      return sum + amt * rate;
    }, 0);
  }, [invoices]);

  const loading = invoicesLoading || deductionsLoading;

  const handleDownloadTaxSummary = useCallback(() => {
    let report = `TAX FILING SUMMARY ${year}\n${'='.repeat(50)}\n\n`;
    report += `Organization: ${currentOrganization?.business_name || '—'}\n\n`;
    report += `INCOME\nTotal Revenue: ${formatCurrency(revenue)}\n\n`;
    report += `DEDUCTIONS\nBusiness: ${formatCurrency(byType?.business || 0)}\nCapital: ${formatCurrency(byType?.capital || 0)}\nPersonal: ${formatCurrency(byType?.personal || 0)}\nTotal: ${formatCurrency((byType?.business || 0) + (byType?.capital || 0) + (byType?.personal || 0))}\n\n`;
    report += `Adjusted Income: ${formatCurrency(adjustedIncome)}\nChargeable Income: ${formatCurrency(chargeableIncome)}\n\n`;
    report += `TAX CALCULATION\nIncome Tax: ${formatCurrency(incomeTax)}\n\n`;
    report += `Generated by CukaiPro - ${formatDate(new Date())}\n`;

    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `tax-summary-${year}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [year, revenue, byType, adjustedIncome, chargeableIncome, incomeTax, currentOrganization]);

  const handleDownloadSSTReport = useCallback(() => {
    const now = new Date();
    const reportDate = formatDate(now);
    const filingPeriod = `${now.toLocaleString('en-MY', { month: 'long' })} ${now.getFullYear()}`;

    const invoiceDetailLines = invoices
      .map((inv) => {
        const dateStr = inv.invoice_date
          ? (typeof inv.invoice_date === 'string' && /^\d{2}\/\d{2}\/\d{4}$/.test(inv.invoice_date)
            ? inv.invoice_date
            : formatDate(inv.invoice_date))
          : '—';
        const amount = Number(inv.amount) || 0;
        const status = inv.lhdn_status || inv.status || 'draft';
        return `Invoice #${String(inv.id).slice(0, 8)}
Client: ${inv.client_name || '—'}
Date: ${dateStr}
Amount: RM ${amount.toFixed(2)}
Status: ${status}
---`;
      })
      .join('\n\n');

    const content = `SST REPORT
==========

Report Date: ${reportDate}
Filing Period: ${filingPeriod}

SUMMARY
-------
Total SST Payable: ${formatCurrency(totalSst)}
Total Invoices: ${invoices.length}

INVOICE DETAILS
---------------
${invoiceDetailLines || '(No invoices)'}

Generated by CukaiPro
`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `sst-report-${now.getMonth() + 1}-${now.getFullYear()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [invoices, totalSst]);

  const handleDownloadFormB = useCallback(() => {
    const content = `LHDN FORM B DATA - YEAR OF ASSESSMENT ${year}
===============================================

Organization: ${currentOrganization?.business_name || '—'}
Generated: ${formatDate(new Date())}

SECTION 3 - GROSS INCOME
------------------------
Gross business income: ${formatCurrency(revenue)}

SECTION 4 - LESS: BUSINESS EXPENSES
-----------------------------------
Total business expenses: ${formatCurrency(byType?.business || 0)}

SECTION 5 - LESS: CAPITAL ALLOWANCE
-----------------------------------
Total capital allowance: ${formatCurrency(byType?.capital || 0)}

ADJUSTED INCOME
---------------
Adjusted income: ${formatCurrency(adjustedIncome)}

SECTION 6 - LESS: PERSONAL RELIEF
---------------------------------
Total personal relief: ${formatCurrency(byType?.personal || 0)}

CHARGEABLE INCOME
-----------------
Chargeable income: ${formatCurrency(chargeableIncome)}

SECTION 7 - TAX CALCULATION
---------------------------
Income tax payable: ${formatCurrency(incomeTax)}

Progressive breakdown:
${(incomeTaxBreakdown || []).map((r) => `  ${r.band} @ ${r.rate}%: ${formatCurrency(r.tax || 0)}`).join('\n')}

---
For manual entry into LHDN e-Filing Form B.
Generated by CukaiPro.
`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `form-b-data-${year}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, [year, revenue, byType, adjustedIncome, chargeableIncome, incomeTax, incomeTaxBreakdown, currentOrganization]);

  const handleDownloadDeductionsCSV = useCallback(() => {
    const headers = 'Category,Type,Amount,Claimable,Date,Year,Receipt\n';
    const rows = deductionsForYear
      .map((d) =>
        [
          (d.category_name || '').replace(/,/g, ';'),
          d.category_type || '',
          d.amount || 0,
          d.claimable_amount || 0,
          d.deduction_date || '',
          d.tax_year || year,
          d.has_receipt ? 'Yes' : 'No',
        ].join(',')
      )
      .join('\n');
    const blob = new Blob([headers + rows], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `deductions-${year}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }, [deductionsForYear, year]);

  const reportCards = [
    {
      title: 'Tax Filing Summary',
      description: 'Income, deductions, and tax calculation for the selected year.',
      icon: 'description',
      color: 'bg-primary/10 text-primary',
      link: '/dashboard/tax-filing',
      actions: [
        { label: 'View Full Report', to: '/dashboard/tax-filing' },
        { label: 'Download TXT', onClick: handleDownloadTaxSummary },
      ],
      stats: [
        { label: 'Revenue', value: formatCurrency(revenue) },
        { label: 'Tax Payable', value: formatCurrency(incomeTax) },
      ],
    },
    {
      title: 'SST Report',
      description: 'Sales and Service Tax summary and invoice details.',
      icon: 'local_atm',
      color: 'bg-emerald-500/10 text-emerald-500',
      actions: [
        { label: 'Download Report', onClick: handleDownloadSSTReport },
      ],
      stats: [
        { label: 'Total SST', value: formatCurrency(totalSst) },
        { label: 'Invoices', value: String(invoices.length) },
      ],
    },
    {
      title: 'Deductions Report',
      description: 'Export all deductions for the year to CSV.',
      icon: 'receipt_long',
      color: 'bg-amber-500/10 text-amber-500',
      link: '/dashboard/deductions',
      actions: [
        { label: 'View Deductions', to: '/dashboard/deductions' },
        { label: 'Export CSV', onClick: handleDownloadDeductionsCSV },
      ],
      stats: [
        { label: 'Total Items', value: String(deductionsForYear.length) },
        {
          label: 'Total Claimable',
          value: formatCurrency(
            deductionsForYear.reduce((s, d) => s + (Number(d.claimable_amount) || 0), 0)
          ),
        },
      ],
    },
    {
      title: 'Form B / LHDN Data',
      description: 'Export data in LHDN Form B structure for manual e-Filing entry.',
      icon: 'summarize',
      color: 'bg-indigo-500/10 text-indigo-500',
      link: '/dashboard/tax-filing',
      actions: [
        { label: 'View Filing Summary', to: '/dashboard/tax-filing' },
        { label: 'Download Form B Data', onClick: handleDownloadFormB },
      ],
      stats: [
        { label: 'Adjusted Income', value: formatCurrency(adjustedIncome) },
        { label: 'Tax Payable', value: formatCurrency(incomeTax) },
      ],
    },
  ];

  return (
    <div className="bg-background-light dark:bg-background-dark min-h-screen flex">
      <Sidebar />
      <main className="ml-64 flex-1 p-8">
        <div className="max-w-6xl mx-auto">
          <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div>
              <h1 className="text-2xl font-bold text-slate-900 dark:text-white">Reports</h1>
              <p className="text-slate-500 dark:text-slate-400 text-sm">
                Generate and export tax reports
              </p>
            </div>
            <select
              value={year}
              onChange={(e) => setYear(Number(e.target.value))}
              className="px-4 py-2.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-custom text-slate-900 dark:text-white text-sm"
            >
              {YEARS.map((y) => (
                <option key={y} value={y}>
                  {y}
                </option>
              ))}
            </select>
          </div>

          {loading ? (
            <ReportsSkeleton />
          ) : (
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              {reportCards.map((card) => (
                <div
                  key={card.title}
                  className="bg-white dark:bg-slate-custom rounded-xl border border-slate-200 dark:border-slate-700 shadow-sm p-6 flex flex-col"
                >
                  <div className={`w-12 h-12 rounded-lg flex items-center justify-center mb-4 ${card.color}`}>
                    <span className="material-icons text-2xl">{card.icon}</span>
                  </div>
                  <h2 className="text-lg font-bold text-slate-900 dark:text-white mb-2">
                    {card.title}
                  </h2>
                  <p className="text-sm text-slate-500 dark:text-slate-400 mb-4 flex-1">
                    {card.description}
                  </p>
                  <div className="space-y-2 mb-4">
                    {card.stats.map((s) => (
                      <div key={s.label} className="flex justify-between text-sm">
                        <span className="text-slate-500 dark:text-slate-400">{s.label}</span>
                        <span className="font-medium text-slate-900 dark:text-white">{s.value}</span>
                      </div>
                    ))}
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {card.actions.map((action) =>
                      action.to ? (
                        <Link
                          key={action.label}
                          to={action.to}
                          className="px-4 py-2 rounded-lg bg-primary text-white text-sm font-medium hover:bg-primary/90 transition-colors"
                        >
                          {action.label}
                        </Link>
                      ) : (
                        <button
                          key={action.label}
                          type="button"
                          onClick={action.onClick}
                          className="px-4 py-2 rounded-lg border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-custom text-sm font-medium hover:bg-slate-50 dark:hover:bg-slate-800/30 transition-colors"
                        >
                          {action.label}
                        </button>
                      )
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}

export default ReportsPage;
