import { useState, useCallback } from 'react';
import PropTypes from 'prop-types';
import { useInvoices } from '../../hooks/useInvoices';
import { formatCurrency, formatDate } from '../../utils/validators';
import Sidebar from '../../components/Sidebar';
import Loading from '../../components/Common/Loading';
import CreateInvoiceModal from './CreateInvoiceModal';
import ViewInvoiceModal from './ViewInvoiceModal';

/**
 * Renders the status badge with color based on status value.
 * @param {string} status - One of draft, sent, paid, cancelled
 * @returns {JSX.Element}
 */
function StatusBadge({ status }) {
  const config = {
    draft: {
      bg: 'bg-slate-custom/10 dark:bg-white/10',
      text: 'text-slate-custom dark:text-white/70',
      dot: 'bg-slate-custom dark:bg-white/60',
    },
    sent: {
      bg: 'bg-blue-100 dark:bg-blue-900/30',
      text: 'text-blue-800 dark:text-blue-300',
      dot: 'bg-blue-600',
    },
    paid: {
      bg: 'bg-primary/10',
      text: 'text-primary',
      dot: 'bg-primary',
    },
    cancelled: {
      bg: 'bg-red-100 dark:bg-red-900/30',
      text: 'text-red-800 dark:text-red-300',
      dot: 'bg-red-600',
    },
  };
  const { bg, text, dot } = config[status] || config.draft;
  const label = status ? status.charAt(0).toUpperCase() + status.slice(1) : 'Draft';

  return (
    <span
      className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${bg} ${text}`}
    >
      <span className={`w-1.5 h-1.5 rounded-full ${dot} mr-1.5`} />
      {label}
    </span>
  );
}

StatusBadge.propTypes = {
  status: PropTypes.string,
};

/**
 * Invoice Manager page (Page 4). Lists invoices from Supabase with create and delete actions.
 */
function InvoiceListPage() {
  const { invoices, loading, error, fetchInvoices, createInvoice, deleteInvoice } = useInvoices();
  const [modalOpen, setModalOpen] = useState(false);
  const [viewInvoice, setViewInvoice] = useState(null);
  const [deletingId, setDeletingId] = useState(null);

  const handleCreateClick = useCallback(() => setModalOpen(true), []);
  const handleModalClose = useCallback(() => setModalOpen(false), []);
  const handleViewClose = useCallback(() => setViewInvoice(null), []);

  /**
   * Handles delete with loading state and error handling.
   * @param {string} id - Invoice id
   */
  const handleDelete = useCallback(
    async (id) => {
      setDeletingId(id);
      try {
        const result = await deleteInvoice(id);
        if (!result.success) {
          // Error already set in hook; optional: toast or inline message
        }
      } finally {
        setDeletingId(null);
      }
    },
    [deleteInvoice]
  );

  const displayDate = (invoice) => {
    const d = invoice.invoice_date;
    if (!d) return '—';
    if (typeof d === 'string' && /^\d{2}\/\d{2}\/\d{4}$/.test(d)) return d;
    return formatDate(d);
  };

  /**
   * Downloads invoice as a formatted .txt file.
   * @param {object} invoice - Invoice object from list
   */
  const handleDownloadTxt = useCallback((invoice) => {
    const d = invoice.invoice_date;
    let dateStr = '—';
    if (d) {
      dateStr =
        typeof d === 'string' && /^\d{2}\/\d{2}\/\d{4}$/.test(d)
          ? d
          : formatDate(d);
    }
    const amountStr =
      invoice.amount != null
        ? formatCurrency(Number(invoice.amount))
        : '—';
    const statusLabel = (invoice.status || 'draft').charAt(0).toUpperCase() + (invoice.status || 'draft').slice(1);
    const idShort = String(invoice.id).slice(0, 8);
    const clientName = invoice.client_name || 'Unknown';
    const safeName = clientName.replace(/[^a-zA-Z0-9-_]/g, '-').replace(/-+/g, '-').slice(0, 50);

    const content = `INVOICE
========

Invoice ID: #${idShort}
Date: ${dateStr}

CLIENT DETAILS
--------------
Name: ${clientName}
TIN: ${invoice.tin || '—'}

INVOICE DETAILS
---------------
Amount: ${amountStr}
Status: ${statusLabel}
Notes: ${invoice.notes || '—'}

Generated by CukaiPro
`;

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `invoice-${idShort}-${safeName}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }, []);

  return (
    <div className="bg-background-light dark:bg-background-dark min-h-screen flex">
      <Sidebar />
      <main className="ml-64 flex-1 p-8">
        <div className="max-w-7xl mx-auto px-6 py-8">
      {/* Page Title Section */}
      <div className="mb-8 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-custom dark:text-white">Invoices</h1>
          <p className="text-sm text-slate-custom/60 dark:text-slate-custom/40">
            Manage your Malaysian SME tax compliance and billing.
          </p>
        </div>
        <button
          type="button"
          onClick={handleCreateClick}
          className="flex items-center justify-center gap-2 bg-primary text-white px-5 py-2.5 rounded-lg hover:bg-primary/90 transition-all font-medium text-sm"
        >
          <span className="material-icons-outlined text-[20px]">add</span>
          Create New Invoice
        </button>
      </div>

      {/* Search and Filter Section */}
      <div className="flex flex-col md:flex-row gap-4 mb-6">
        <div className="relative flex-grow">
          <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-slate-custom/40">
            <span className="material-icons-outlined">search</span>
          </span>
          <input
            type="text"
            placeholder="Search by client, invoice number, or amount..."
            className="w-full pl-10 pr-4 py-2.5 bg-white dark:bg-background-dark border border-slate-custom/10 dark:border-white/10 rounded-lg focus:ring-2 focus:ring-primary/50 focus:border-primary outline-none transition-all text-sm"
          />
        </div>
        <button
          type="button"
          className="flex items-center justify-center gap-2 bg-white dark:bg-background-dark border border-slate-custom/10 dark:border-white/10 px-4 py-2.5 rounded-lg text-slate-custom/70 hover:bg-slate-custom/5 transition-all text-sm font-medium"
        >
          <span className="material-icons-outlined text-[20px] text-primary">tune</span>
          Filter
        </button>
        <button
          type="button"
          className="flex items-center justify-center gap-2 bg-white dark:bg-background-dark border border-slate-custom/10 dark:border-white/10 px-4 py-2.5 rounded-lg text-slate-custom/70 hover:bg-slate-custom/5 transition-all text-sm font-medium"
        >
          <span className="material-icons-outlined text-[20px]">download_for_offline</span>
          Export CSV
        </button>
      </div>

      {/* Error message */}
      {error && (
        <div className="mb-6 p-4 rounded-lg bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-300 text-sm">
          {error}
        </div>
      )}

      {/* Loading spinner */}
      {loading && !invoices.length && (
        <div className="flex justify-center py-16">
          <Loading size="lg" text="Loading invoices..." />
        </div>
      )}

      {/* Main Table Card */}
      {(!loading || invoices.length > 0) && (
        <div className="bg-white dark:bg-background-dark border border-slate-custom/10 dark:border-white/10 rounded-lg shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead className="bg-slate-custom/5 dark:bg-white/5 text-slate-custom/60 dark:text-white/60 text-xs font-semibold uppercase tracking-wider">
                <tr>
                  <th className="px-6 py-4 border-b border-slate-custom/10 dark:border-white/10">
                    Date
                  </th>
                  <th className="px-6 py-4 border-b border-slate-custom/10 dark:border-white/10">
                    Client
                  </th>
                  <th className="px-6 py-4 border-b border-slate-custom/10 dark:border-white/10">
                    Invoice ID
                  </th>
                  <th className="px-6 py-4 border-b border-slate-custom/10 dark:border-white/10 text-right">
                    Amount (MYR)
                  </th>
                  <th className="px-6 py-4 border-b border-slate-custom/10 dark:border-white/10">
                    LHDN Status
                  </th>
                  <th className="px-6 py-4 border-b border-slate-custom/10 dark:border-white/10 text-right">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-custom/10 dark:divide-white/10">
                {invoices.length === 0 && !loading && (
                  <tr>
                    <td
                      colSpan={6}
                      className="px-6 py-12 text-center text-sm text-slate-custom/60 dark:text-white/60"
                    >
                      No invoices yet. Create your first invoice.
                    </td>
                  </tr>
                )}
                {invoices.map((invoice) => (
                  <tr
                    key={invoice.id}
                    className="hover:bg-primary/5 transition-colors group"
                  >
                    <td className="px-6 py-4 text-sm font-medium">
                      {displayDate(invoice)}
                    </td>
                    <td className="px-6 py-4 text-sm">
                      <div className="font-medium text-slate-custom dark:text-white">
                        {invoice.client_name || '—'}
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm font-mono text-slate-custom/60">
                      #{String(invoice.id).slice(0, 8)}
                    </td>
                    <td className="px-6 py-4 text-sm text-right font-semibold">
                      {invoice.amount != null
                        ? formatCurrency(Number(invoice.amount))
                        : '—'}
                    </td>
                    <td className="px-6 py-4">
                      <StatusBadge status={invoice.status || 'draft'} />
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex items-center justify-end gap-3 text-slate-custom/40 group-hover:text-slate-custom">
                        <button
                          type="button"
                          onClick={() => setViewInvoice(invoice)}
                          className="hover:text-primary transition-colors"
                          aria-label="View invoice"
                        >
                          <span className="material-icons-outlined text-[20px]">
                            visibility
                          </span>
                        </button>
                        <button
                          type="button"
                          onClick={() => handleDownloadTxt(invoice)}
                          className="hover:text-primary transition-colors"
                          aria-label="Download invoice"
                        >
                          <span className="material-icons-outlined text-[20px]">
                            file_download
                          </span>
                        </button>
                        <button
                          type="button"
                          onClick={() => handleDelete(invoice.id)}
                          disabled={deletingId === invoice.id}
                          className="hover:text-red-600 transition-colors disabled:opacity-50"
                          aria-label="Delete invoice"
                        >
                          {deletingId === invoice.id ? (
                            <span className="material-icons-outlined text-[20px] animate-spin">
                              hourglass_empty
                            </span>
                          ) : (
                            <span className="material-icons-outlined text-[20px]">
                              delete
                            </span>
                          )}
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
          {/* Pagination Section */}
          {invoices.length > 0 && (
            <div className="px-6 py-4 flex items-center justify-between bg-slate-custom/5 dark:bg-white/5 border-t border-slate-custom/10 dark:border-white/10">
              <span className="text-xs text-slate-custom/60">
                Showing 1 to {invoices.length} of {invoices.length} entries
              </span>
              <div className="flex items-center gap-2">
                <button
                  type="button"
                  disabled
                  className="p-1.5 rounded border border-slate-custom/10 dark:border-white/10 text-slate-custom/60 hover:bg-white transition-all disabled:opacity-50"
                >
                  <span className="material-icons-outlined text-sm leading-none">
                    chevron_left
                  </span>
                </button>
                <button
                  type="button"
                  className="px-3 py-1 text-xs font-medium rounded bg-primary text-white"
                >
                  1
                </button>
                <button
                  type="button"
                  className="p-1.5 rounded border border-slate-custom/10 dark:border-white/10 text-slate-custom/60 hover:bg-white transition-all"
                >
                  <span className="material-icons-outlined text-sm leading-none">
                    chevron_right
                  </span>
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {/* System Status Summary Footer */}
      <div className="mt-8 grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-primary/5 border border-primary/10 p-4 rounded-xl flex items-center gap-4">
          <div className="w-10 h-10 rounded-lg bg-primary/20 flex items-center justify-center text-primary">
            <span className="material-icons-outlined">verified</span>
          </div>
          <div>
            <div className="text-xs text-slate-custom/60 uppercase font-semibold">
              Tax Validated
            </div>
            <div className="text-xl font-bold text-primary">
              RM 0.00
            </div>
          </div>
        </div>
        <div className="bg-slate-custom/5 border border-slate-custom/10 p-4 rounded-xl flex items-center gap-4">
          <div className="w-10 h-10 rounded-lg bg-slate-custom/10 flex items-center justify-center text-slate-custom">
            <span className="material-icons-outlined">pending_actions</span>
          </div>
          <div>
            <div className="text-xs text-slate-custom/60 uppercase font-semibold">
              Processing
            </div>
            <div className="text-xl font-bold text-slate-custom">RM 0.00</div>
          </div>
        </div>
        <div className="bg-red-50 dark:bg-red-900/20 border border-red-100 dark:border-red-800 p-4 rounded-xl flex items-center gap-4">
          <div className="w-10 h-10 rounded-lg bg-red-100 dark:bg-red-900/50 flex items-center justify-center text-red-600 dark:text-red-400">
            <span className="material-icons-outlined">report_problem</span>
          </div>
          <div>
            <div className="text-xs text-slate-custom/60 uppercase font-semibold">
              Action Required
            </div>
            <div className="text-xl font-bold text-red-600 dark:text-red-400">RM 0.00</div>
          </div>
        </div>
      </div>

      <CreateInvoiceModal
        isOpen={modalOpen}
        onClose={handleModalClose}
        onCreateInvoice={createInvoice}
        onSuccess={handleModalClose}
      />
      <ViewInvoiceModal
        isOpen={!!viewInvoice}
        onClose={handleViewClose}
        invoice={viewInvoice}
      />
        </div>
      </main>
    </div>
  );
}

export default InvoiceListPage;
