import { useState, useRef, useEffect } from 'react';
import PropTypes from 'prop-types';
import { formatCurrency, formatDate } from '../../utils/validators';
import Button from '../../components/Common/Button';
import AuditTimeline from '../../components/Common/AuditTimeline';
import { useAuditLog } from '../../hooks/useAuditLog';

const STATUS_BADGE_CONFIG = {
  draft: {
    bg: 'bg-slate-custom/10 dark:bg-white/10',
    text: 'text-slate-custom dark:text-white/70',
    dot: 'bg-slate-custom dark:bg-white/60',
  },
  sent: {
    bg: 'bg-blue-100 dark:bg-blue-900/30',
    text: 'text-blue-800 dark:text-blue-300',
    dot: 'bg-blue-600',
  },
  paid: {
    bg: 'bg-primary/10',
    text: 'text-primary',
    dot: 'bg-primary',
  },
  cancelled: {
    bg: 'bg-red-100 dark:bg-red-900/30',
    text: 'text-red-800 dark:text-red-300',
    dot: 'bg-red-600',
  },
};

/**
 * Modal for viewing invoice details. Displays all fields and offers Close / Download PDF.
 * @param {boolean} isOpen - Whether the modal is visible
 * @param {function} onClose - Callback when modal should close
 * @param {object|null} invoice - The invoice object (id, client_name, tin, amount, invoice_date, notes, status)
 */
function ViewInvoiceModal({ isOpen, onClose, invoice }) {
  const modalRef = useRef(null);
  const printRef = useRef(null);

  /** Close when clicking backdrop. */
  useEffect(() => {
    const handleClickOutside = (e) => {
      if (modalRef.current && !modalRef.current.contains(e.target)) {
        onClose();
      }
    };
    if (isOpen) {
      document.addEventListener('mousedown', handleClickOutside);
      return () => document.removeEventListener('mousedown', handleClickOutside);
    }
  }, [isOpen, onClose]);

  if (!isOpen) return null;
  if (!invoice) return null;

  const displayDate = () => {
    const d = invoice.invoice_date;
    if (!d) return '—';
    if (typeof d === 'string' && /^\d{2}\/\d{2}\/\d{4}$/.test(d)) return d;
    return formatDate(d);
  };

  const status = invoice.status || 'draft';
  const config = STATUS_BADGE_CONFIG[status] || STATUS_BADGE_CONFIG.draft;
  const statusLabel = status.charAt(0).toUpperCase() + status.slice(1);

  const amountFormatted =
    invoice.amount != null
      ? formatCurrency(Number(invoice.amount))
      : '—';

  /**
   * Opens print dialog so user can save as PDF.
   */
  const handleDownloadPDF = () => {
    if (!printRef.current) return;
    const printContent = printRef.current.innerHTML;
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head><title>Invoice ${String(invoice.id).slice(0, 8)}</title></head>
        <body style="font-family: Inter, sans-serif; padding: 24px; color: #1E293B;">
          ${printContent}
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 250);
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50"
      role="dialog"
      aria-modal="true"
      aria-labelledby="view-invoice-title"
    >
      <div
        ref={modalRef}
        className="bg-white dark:bg-background-dark border border-slate-custom/10 dark:border-white/10 rounded-xl shadow-xl max-w-md w-full max-h-[90vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="p-6">
          <h2
            id="view-invoice-title"
            className="text-xl font-bold text-slate-custom dark:text-white mb-1"
          >
            Invoice Details
          </h2>
          <p className="text-sm text-slate-custom/60 dark:text-slate-custom/40 mb-6">
            View invoice information.
          </p>

          {/* Hidden content for print/PDF (copied to new window on Download PDF) */}
          <div ref={printRef} className="sr-only" aria-hidden="true">
            <h1 className="text-lg font-bold mb-4">INVOICE</h1>
            <p><strong>Invoice ID:</strong> #{String(invoice.id).slice(0, 8)}</p>
            <p><strong>Date:</strong> {displayDate()}</p>
            <p><strong>Client:</strong> {invoice.client_name || '—'}</p>
            <p><strong>TIN:</strong> {invoice.tin || '—'}</p>
            <p><strong>Amount:</strong> {amountFormatted}</p>
            <p><strong>Status:</strong> {statusLabel}</p>
            {invoice.notes && <p><strong>Notes:</strong> {invoice.notes}</p>}
            <p className="mt-6 text-sm text-slate-500">Generated by CukaiPro</p>
          </div>

          <div className="space-y-4">
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-custom/60 dark:text-white/60 mb-1">
                Invoice ID
              </label>
              <p className="text-sm font-mono text-slate-custom dark:text-white">
                #{String(invoice.id).slice(0, 8)}
              </p>
            </div>
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-custom/60 dark:text-white/60 mb-1">
                Client Name
              </label>
              <p className="text-sm text-slate-custom dark:text-white flex items-center gap-2">
                <span className="material-icons-outlined text-[18px] text-slate-custom/40">person</span>
                {invoice.client_name || '—'}
              </p>
            </div>
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-custom/60 dark:text-white/60 mb-1">
                TIN
              </label>
              <p className="text-sm text-slate-custom dark:text-white flex items-center gap-2">
                <span className="material-icons-outlined text-[18px] text-slate-custom/40">badge</span>
                {invoice.tin || '—'}
              </p>
            </div>
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-custom/60 dark:text-white/60 mb-1">
                Amount
              </label>
              <p className="text-sm font-semibold text-slate-custom dark:text-white flex items-center gap-2">
                <span className="material-icons-outlined text-[18px] text-slate-custom/40">payments</span>
                {amountFormatted}
              </p>
            </div>
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-custom/60 dark:text-white/60 mb-1">
                Invoice Date
              </label>
              <p className="text-sm text-slate-custom dark:text-white flex items-center gap-2">
                <span className="material-icons-outlined text-[18px] text-slate-custom/40">calendar_today</span>
                {displayDate()}
              </p>
            </div>
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-custom/60 dark:text-white/60 mb-1">
                Notes
              </label>
              <p className="text-sm text-slate-custom dark:text-white flex items-start gap-2">
                <span className="material-icons-outlined text-[18px] text-slate-custom/40 mt-0.5">notes</span>
                {invoice.notes || '—'}
              </p>
            </div>
            <div>
              <label className="block text-xs font-semibold uppercase tracking-wider text-slate-custom/60 dark:text-white/60 mb-1">
                LHDN Status
              </label>
              <span
                className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${config.bg} ${config.text}`}
              >
                <span className={`w-1.5 h-1.5 rounded-full ${config.dot} mr-1.5`} />
                {statusLabel}
              </span>
            </div>

            <div className="border-t border-slate-custom/10 dark:border-white/10 pt-4">
              <button
                type="button"
                onClick={() => setShowHistory((prev) => !prev)}
                className="flex items-center gap-2 text-sm font-medium text-slate-custom/60 dark:text-white/60 hover:text-primary dark:hover:text-emerald-400"
              >
                <span className="material-icons-outlined text-[18px]">history</span>
                {showHistory ? 'Hide history' : 'View history'}
              </button>
              {showHistory && (
                <div className="mt-3 p-3 rounded-lg bg-slate-custom/5 dark:bg-white/5">
                  <AuditTimeline
                    entries={entries}
                    loading={historyLoading}
                    error={historyError}
                    emptyMessage="No changes recorded yet."
                  />
                </div>
              )}
            </div>
          </div>

          <div className="flex gap-3 pt-6 mt-6 border-t border-slate-custom/10 dark:border-white/10">
            <Button
              type="button"
              variant="secondary"
              onClick={onClose}
              className="flex-1"
            >
              Close
            </Button>
            <Button
              type="button"
              onClick={handleDownloadPDF}
              className="flex-1 bg-primary text-white hover:bg-primary/90"
            >
              Download PDF
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}

ViewInvoiceModal.propTypes = {
  isOpen: PropTypes.bool.isRequired,
  onClose: PropTypes.func.isRequired,
  invoice: PropTypes.shape({
    id: PropTypes.string,
    client_name: PropTypes.string,
    tin: PropTypes.string,
    amount: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
    invoice_date: PropTypes.string,
    notes: PropTypes.string,
    status: PropTypes.string,
  }),
};

export default ViewInvoiceModal;
